language: php

php:
    - 5.3
    - 5.4

branches:
    only:
        - master
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - sleep 5
script:
    - vendor/bin/phpspec run -f dot